"""Human-readable and machine-readable report generation."""

import html
import json
from pathlib import Path
from typing import List
from urllib.parse import quote

from .models import DocumentDiff, RunSummary


def _markdown_document(document: DocumentDiff) -> List[str]:
    lines = [
        "## `{}`".format(document.path.replace("`", "\\`")),
        "",
        "- Status: **{}**".format(document.status),
        "- Pages/slides: {} → {}".format(document.base_pages, document.current_pages),
        "- Changed pages/slides: {}".format(document.changed_pages),
        "",
    ]
    if document.errors:
        lines.extend(["### Errors", ""])
        lines.extend("- {}".format(error) for error in document.errors)
        lines.append("")
    if document.pages:
        lines.extend(["### Visual review", ""])
        for page in document.pages:
            lines.extend(
                [
                    "#### Page/slide {} · {} · {:.2%} changed".format(
                        page.index, page.status, page.change_ratio
                    ),
                    "",
                    "![Page/slide {} visual diff]({})".format(
                        page.index, quote(page.diff_image)
                    ),
                    "",
                ]
            )
    if document.text_diff:
        lines.extend(["### Extracted text diff", "", "```diff", document.text_diff, "```", ""])
    return lines


def render_markdown(summary: RunSummary) -> str:
    lines = [
        "# Office Diff Report",
        "",
        "Compared `{}` → `{}` with {}.".format(
            summary.base_ref, summary.head_ref, summary.render_engine
        ),
        "",
        "| Documents | Changed pages/slides | Errors |",
        "|---:|---:|---:|",
        "| {} | {} | {} |".format(
            len(summary.documents), summary.changed_pages, summary.error_count
        ),
        "",
    ]
    if not summary.documents:
        lines.extend(["No changed `.docx` or `.pptx` files were found.", ""])
    for document in summary.documents:
        lines.extend(_markdown_document(document))
    lines.extend(
        [
            "---",
            "",
            "Generated by [Office Diff Action](https://github.com/zhuyep/office-diff-action).",
            "",
        ]
    )
    return "\n".join(lines)


def _html_document(document: DocumentDiff) -> str:
    parts = [
        '<section class="document">',
        "<h2>{}</h2>".format(html.escape(document.path)),
        '<p><span class="status">{}</span> {} → {} pages/slides; {} changed.</p>'.format(
            html.escape(document.status),
            document.base_pages,
            document.current_pages,
            document.changed_pages,
        ),
    ]
    if document.errors:
        parts.append('<div class="errors"><strong>Errors</strong><ul>')
        parts.extend("<li>{}</li>".format(html.escape(error)) for error in document.errors)
        parts.append("</ul></div>")
    for page in document.pages:
        parts.extend(
            [
                "<h3>Page/slide {} · {} · {:.2%} changed</h3>".format(
                    page.index, html.escape(page.status), page.change_ratio
                ),
                '<a href="{0}"><img loading="lazy" src="{0}" alt="Page/slide {1} visual diff"></a>'.format(
                    quote(page.diff_image), page.index
                ),
            ]
        )
    if document.text_diff:
        parts.extend(
            ["<h3>Extracted text diff</h3>", "<pre>{}</pre>".format(html.escape(document.text_diff))]
        )
    parts.append("</section>")
    return "\n".join(parts)


def render_html(summary: RunSummary) -> str:
    documents = "\n".join(_html_document(document) for document in summary.documents)
    if not documents:
        documents = "<p>No changed DOCX or PPTX files were found.</p>"
    return """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Office Diff Report</title>
  <style>
    :root {{ color-scheme: light dark; }}
    body {{ font: 16px/1.55 system-ui, sans-serif; max-width: 1180px; margin: 0 auto; padding: 32px 20px 80px; }}
    header {{ border-bottom: 1px solid #9ca3af55; margin-bottom: 32px; }}
    .summary {{ display: flex; gap: 12px; flex-wrap: wrap; margin: 20px 0; }}
    .metric {{ border: 1px solid #9ca3af66; border-radius: 10px; padding: 10px 14px; }}
    .document {{ margin-top: 48px; }}
    .status {{ font-weight: 700; text-transform: uppercase; }}
    .errors {{ border-left: 4px solid #dc2626; padding: 10px 16px; background: #dc262611; }}
    img {{ width: 100%; height: auto; border: 1px solid #9ca3af55; border-radius: 8px; }}
    pre {{ overflow-x: auto; padding: 16px; border-radius: 8px; background: #6b72801a; }}
    code {{ font-family: ui-monospace, monospace; }}
  </style>
</head>
<body>
  <header>
    <h1>Office Diff Report</h1>
    <p><code>{base}</code> → <code>{head}</code> · {engine}</p>
    <div class="summary">
      <span class="metric"><strong>{documents}</strong> documents</span>
      <span class="metric"><strong>{pages}</strong> changed pages/slides</span>
      <span class="metric"><strong>{errors}</strong> errors</span>
    </div>
  </header>
  {body}
</body>
</html>
""".format(
        base=html.escape(summary.base_ref),
        head=html.escape(summary.head_ref),
        engine=html.escape(summary.render_engine),
        documents=len(summary.documents),
        pages=summary.changed_pages,
        errors=summary.error_count,
        body=documents,
    )


def write_reports(summary: RunSummary, output_dir: Path) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    (output_dir / "summary.json").write_text(
        json.dumps(summary.to_dict(), ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    (output_dir / "report.md").write_text(render_markdown(summary), encoding="utf-8")
    (output_dir / "index.html").write_text(render_html(summary), encoding="utf-8")
